/**
 * generated by Xtext 2.18.0
 */
package org.xtext.myCsv;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Programm</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.myCsv.Programm#getStmts <em>Stmts</em>}</li>
 * </ul>
 *
 * @see org.xtext.myCsv.MyCsvPackage#getProgramm()
 * @model
 * @generated
 */
public interface Programm extends EObject
{
  /**
   * Returns the value of the '<em><b>Stmts</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.myCsv.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stmts</em>' containment reference list.
   * @see org.xtext.myCsv.MyCsvPackage#getProgramm_Stmts()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStmts();

} // Programm
