/**
 * generated by Xtext 2.23.0
 */
package org.xtext.myCsv;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.myCsv.AndExpression#getLhs <em>Lhs</em>}</li>
 *   <li>{@link org.xtext.myCsv.AndExpression#getRhs <em>Rhs</em>}</li>
 * </ul>
 *
 * @see org.xtext.myCsv.MyCsvPackage#getAndExpression()
 * @model
 * @generated
 */
public interface AndExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lhs</em>' containment reference.
   * @see #setLhs(UnaryLogExpression)
   * @see org.xtext.myCsv.MyCsvPackage#getAndExpression_Lhs()
   * @model containment="true"
   * @generated
   */
  UnaryLogExpression getLhs();

  /**
   * Sets the value of the '{@link org.xtext.myCsv.AndExpression#getLhs <em>Lhs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lhs</em>' containment reference.
   * @see #getLhs()
   * @generated
   */
  void setLhs(UnaryLogExpression value);

  /**
   * Returns the value of the '<em><b>Rhs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.myCsv.UnaryLogExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rhs</em>' containment reference list.
   * @see org.xtext.myCsv.MyCsvPackage#getAndExpression_Rhs()
   * @model containment="true"
   * @generated
   */
  EList<UnaryLogExpression> getRhs();

} // AndExpression
