/**
 * generated by Xtext 2.23.0
 */
package org.xtext.myCsv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.myCsv.DeleteField#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @see org.xtext.myCsv.MyCsvPackage#getDeleteField()
 * @model
 * @generated
 */
public interface DeleteField extends Delete
{
  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference.
   * @see #setFields(FieldIndex)
   * @see org.xtext.myCsv.MyCsvPackage#getDeleteField_Fields()
   * @model containment="true"
   * @generated
   */
  FieldIndex getFields();

  /**
   * Sets the value of the '{@link org.xtext.myCsv.DeleteField#getFields <em>Fields</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fields</em>' containment reference.
   * @see #getFields()
   * @generated
   */
  void setFields(FieldIndex value);

} // DeleteField
