/**
 * generated by Xtext 2.23.0
 */
package org.xtext.myCsv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.myCsv.MyCsvPackage#getDelete()
 * @model
 * @generated
 */
public interface Delete extends Statement
{
} // Delete
