/**
 * generated by Xtext 2.23.0
 */
package org.xtext.myCsv;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Calcul Primary</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.myCsv.MyCsvPackage#getExpressionCalculPrimary()
 * @model
 * @generated
 */
public interface ExpressionCalculPrimary extends EObject
{
} // ExpressionCalculPrimary
