/**
 * generated by Xtext 2.23.0
 */
package org.xtext.myCsv;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field Index Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.myCsv.FieldIndexName#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @see org.xtext.myCsv.MyCsvPackage#getFieldIndexName()
 * @model
 * @generated
 */
public interface FieldIndexName extends FieldIndex
{
  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.myCsv.Field}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see org.xtext.myCsv.MyCsvPackage#getFieldIndexName_Fields()
   * @model containment="true"
   * @generated
   */
  EList<Field> getFields();

} // FieldIndexName
