/**
 * generated by Xtext 2.23.0
 */
package org.xtext.myCsv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Line Index Cond</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.myCsv.LineIndexCond#getCond <em>Cond</em>}</li>
 * </ul>
 *
 * @see org.xtext.myCsv.MyCsvPackage#getLineIndexCond()
 * @model
 * @generated
 */
public interface LineIndexCond extends LineIndex
{
  /**
   * Returns the value of the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond</em>' containment reference.
   * @see #setCond(ExpressionLog)
   * @see org.xtext.myCsv.MyCsvPackage#getLineIndexCond_Cond()
   * @model containment="true"
   * @generated
   */
  ExpressionLog getCond();

  /**
   * Sets the value of the '{@link org.xtext.myCsv.LineIndexCond#getCond <em>Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cond</em>' containment reference.
   * @see #getCond()
   * @generated
   */
  void setCond(ExpressionLog value);

} // LineIndexCond
