/**
 * generated by Xtext 2.23.0
 */
package org.xtext.myCsv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Modify</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.myCsv.MyCsvPackage#getModify()
 * @model
 * @generated
 */
public interface Modify extends Statement
{
} // Modify
