/**
 * generated by Xtext 2.23.0
 */
package org.xtext.myCsv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Modify Cell</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.myCsv.ModifyCell#getCell <em>Cell</em>}</li>
 *   <li>{@link org.xtext.myCsv.ModifyCell#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.myCsv.MyCsvPackage#getModifyCell()
 * @model
 * @generated
 */
public interface ModifyCell extends Modify
{
  /**
   * Returns the value of the '<em><b>Cell</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cell</em>' containment reference.
   * @see #setCell(CellIndex)
   * @see org.xtext.myCsv.MyCsvPackage#getModifyCell_Cell()
   * @model containment="true"
   * @generated
   */
  CellIndex getCell();

  /**
   * Sets the value of the '{@link org.xtext.myCsv.ModifyCell#getCell <em>Cell</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cell</em>' containment reference.
   * @see #getCell()
   * @generated
   */
  void setCell(CellIndex value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Value)
   * @see org.xtext.myCsv.MyCsvPackage#getModifyCell_Value()
   * @model containment="true"
   * @generated
   */
  Value getValue();

  /**
   * Sets the value of the '{@link org.xtext.myCsv.ModifyCell#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Value value);

} // ModifyCell
