/**
 * generated by Xtext 2.23.0
 */
package org.xtext.myCsv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Print Table</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.myCsv.MyCsvPackage#getPrintTable()
 * @model
 * @generated
 */
public interface PrintTable extends Print
{
} // PrintTable
