/**
 * generated by Xtext 2.23.0
 */
package org.xtext.myCsv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Print Line</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.myCsv.PrintLine#getLines <em>Lines</em>}</li>
 * </ul>
 *
 * @see org.xtext.myCsv.MyCsvPackage#getPrintLine()
 * @model
 * @generated
 */
public interface PrintLine extends Print
{
  /**
   * Returns the value of the '<em><b>Lines</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lines</em>' containment reference.
   * @see #setLines(LineIndex)
   * @see org.xtext.myCsv.MyCsvPackage#getPrintLine_Lines()
   * @model containment="true"
   * @generated
   */
  LineIndex getLines();

  /**
   * Sets the value of the '{@link org.xtext.myCsv.PrintLine#getLines <em>Lines</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lines</em>' containment reference.
   * @see #getLines()
   * @generated
   */
  void setLines(LineIndex value);

} // PrintLine
