/**
 * generated by Xtext 2.23.0
 */
package org.xtext.myCsv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Projection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.myCsv.Projection#getField <em>Field</em>}</li>
 * </ul>
 *
 * @see org.xtext.myCsv.MyCsvPackage#getProjection()
 * @model
 * @generated
 */
public interface Projection extends Statement
{
  /**
   * Returns the value of the '<em><b>Field</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field</em>' containment reference.
   * @see #setField(FieldIndex)
   * @see org.xtext.myCsv.MyCsvPackage#getProjection_Field()
   * @model containment="true"
   * @generated
   */
  FieldIndex getField();

  /**
   * Sets the value of the '{@link org.xtext.myCsv.Projection#getField <em>Field</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field</em>' containment reference.
   * @see #getField()
   * @generated
   */
  void setField(FieldIndex value);

} // Projection
