/**
 * generated by Xtext 2.23.0
 */
package org.xtext.myCsv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.myCsv.Select#getLine <em>Line</em>}</li>
 * </ul>
 *
 * @see org.xtext.myCsv.MyCsvPackage#getSelect()
 * @model
 * @generated
 */
public interface Select extends Statement
{
  /**
   * Returns the value of the '<em><b>Line</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Line</em>' containment reference.
   * @see #setLine(LineIndex)
   * @see org.xtext.myCsv.MyCsvPackage#getSelect_Line()
   * @model containment="true"
   * @generated
   */
  LineIndex getLine();

  /**
   * Sets the value of the '{@link org.xtext.myCsv.Select#getLine <em>Line</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Line</em>' containment reference.
   * @see #getLine()
   * @generated
   */
  void setLine(LineIndex value);

} // Select
