/**
 * generated by Xtext 2.23.0
 */
package org.xtext.myCsv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Store</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.myCsv.Store#getPath <em>Path</em>}</li>
 *   <li>{@link org.xtext.myCsv.Store#isSepDefined <em>Sep Defined</em>}</li>
 *   <li>{@link org.xtext.myCsv.Store#getSep <em>Sep</em>}</li>
 *   <li>{@link org.xtext.myCsv.Store#isNoHeader <em>No Header</em>}</li>
 * </ul>
 *
 * @see org.xtext.myCsv.MyCsvPackage#getStore()
 * @model
 * @generated
 */
public interface Store extends Statement
{
  /**
   * Returns the value of the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' containment reference.
   * @see #setPath(Path)
   * @see org.xtext.myCsv.MyCsvPackage#getStore_Path()
   * @model containment="true"
   * @generated
   */
  Path getPath();

  /**
   * Sets the value of the '{@link org.xtext.myCsv.Store#getPath <em>Path</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' containment reference.
   * @see #getPath()
   * @generated
   */
  void setPath(Path value);

  /**
   * Returns the value of the '<em><b>Sep Defined</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sep Defined</em>' attribute.
   * @see #setSepDefined(boolean)
   * @see org.xtext.myCsv.MyCsvPackage#getStore_SepDefined()
   * @model
   * @generated
   */
  boolean isSepDefined();

  /**
   * Sets the value of the '{@link org.xtext.myCsv.Store#isSepDefined <em>Sep Defined</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sep Defined</em>' attribute.
   * @see #isSepDefined()
   * @generated
   */
  void setSepDefined(boolean value);

  /**
   * Returns the value of the '<em><b>Sep</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sep</em>' attribute.
   * @see #setSep(String)
   * @see org.xtext.myCsv.MyCsvPackage#getStore_Sep()
   * @model
   * @generated
   */
  String getSep();

  /**
   * Sets the value of the '{@link org.xtext.myCsv.Store#getSep <em>Sep</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sep</em>' attribute.
   * @see #getSep()
   * @generated
   */
  void setSep(String value);

  /**
   * Returns the value of the '<em><b>No Header</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>No Header</em>' attribute.
   * @see #setNoHeader(boolean)
   * @see org.xtext.myCsv.MyCsvPackage#getStore_NoHeader()
   * @model
   * @generated
   */
  boolean isNoHeader();

  /**
   * Sets the value of the '{@link org.xtext.myCsv.Store#isNoHeader <em>No Header</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>No Header</em>' attribute.
   * @see #isNoHeader()
   * @generated
   */
  void setNoHeader(boolean value);

} // Store
