/*
 * generated by Xtext 2.18.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.mycsv.ui.internal.MycsvActivator;

public class MyCsvUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MycsvActivator.getInstance().getInjector("org.xtext.MyCsv");
	}

}
