/*
 * generated by Xtext 2.23.0
 */
package org.xtext.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.myCsv.Program
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl
import org.eclipse.emf.common.util.URI
import org.xtext.MyCsvStandaloneSetupGenerated
import org.xtext.generator.MyCsvVisitor

@ExtendWith(InjectionExtension)
@InjectWith(MyCsvInjectorProvider)
class MyCsvParsingTest {
	/*
	@Inject
	ParseHelper<Program> parseHelper
	*/
	
	@Test
	def void loadModel() {
		/*val result = parseHelper.parse('''
			Load "mycsv.csv"
			Load "mycsv12.csv" sep="'"
			ExportJson "mycsv12.json"
			Projection 1 2   33
			Load "mycsv2.csv" noheader
			Store "ici"
			Store "labas" sep="("
		''')*/
		val result= loadMyCSV(URI.createURI("examples/test1.mycsv"))
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val prettyPrinter = new MyCsvVisitor
		prettyPrinter.prettyPrint(result)
	}
	
	def loadMyCSV(URI uri){
		new MyCsvStandaloneSetupGenerated().createInjectorAndDoEMFRegistration()
		var res= new ResourceSetImpl().getResource(uri, true);
		res.contents.get(0) as Program
	}
}
