/*
 * generated by Xtext 2.23.0
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyCsvUiModule extends AbstractMyCsvUiModule {

	public MyCsvUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
