/**
 * generated by Xtext 2.23.0
 */
package org.xtext.myCsv.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.myCsv.InsertLine;
import org.xtext.myCsv.MyCsvPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Insert Line</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InsertLineImpl extends InsertImpl implements InsertLine
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InsertLineImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyCsvPackage.Literals.INSERT_LINE;
  }

} //InsertLineImpl
