/**
 * generated by Xtext 2.23.0
 */
package org.xtext.myCsv.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.myCsv.MyCsvPackage;
import org.xtext.myCsv.PrintTable;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Print Table</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PrintTableImpl extends PrintImpl implements PrintTable
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrintTableImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyCsvPackage.Literals.PRINT_TABLE;
  }

} //PrintTableImpl
