/*
 * generated by Xtext 2.18.0
 */
package org.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MyCsvRuntimeModule extends AbstractMyCsvRuntimeModule {
}
