/*
 * generated by Xtext 2.18.0
 */
package org.xtext.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.MyCsvRuntimeModule
import org.xtext.MyCsvStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MyCsvIdeSetup extends MyCsvStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MyCsvRuntimeModule, new MyCsvIdeModule))
	}
	
}
